// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqRlDMDqFfls8NcZBbgd9dV2IripOnZXY',
    appId: '1:148289627904:web:d73a4a9270e3e2a8d875e5',
    messagingSenderId: '148289627904',
    projectId: 'inspireme-bf9ff',
    authDomain: 'inspireme-bf9ff.firebaseapp.com',
    storageBucket: 'inspireme-bf9ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgsf9jLHTuPf_Ek5Qy8WzI3xGVj6Sul8',
    appId: '1:148289627904:android:446a7e2f6d1adb4fd875e5',
    messagingSenderId: '148289627904',
    projectId: 'inspireme-bf9ff',
    storageBucket: 'inspireme-bf9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCCTiDnx4h6f5iL9MKL6GkVc6FYN_HTA',
    appId: '1:148289627904:ios:13db479950ca6863d875e5',
    messagingSenderId: '148289627904',
    projectId: 'inspireme-bf9ff',
    storageBucket: 'inspireme-bf9ff.firebasestorage.app',
    iosBundleId: 'com.example.inspireme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCCTiDnx4h6f5iL9MKL6GkVc6FYN_HTA',
    appId: '1:148289627904:ios:13db479950ca6863d875e5',
    messagingSenderId: '148289627904',
    projectId: 'inspireme-bf9ff',
    storageBucket: 'inspireme-bf9ff.firebasestorage.app',
    iosBundleId: 'com.example.inspireme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqRlDMDqFfls8NcZBbgd9dV2IripOnZXY',
    appId: '1:148289627904:web:7995edc99ca20f74d875e5',
    messagingSenderId: '148289627904',
    projectId: 'inspireme-bf9ff',
    authDomain: 'inspireme-bf9ff.firebaseapp.com',
    storageBucket: 'inspireme-bf9ff.firebasestorage.app',
  );
}
